### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by Jenia3377543** [wapchief/LikeStarAnimation#1]
the icons that i put in the array dont display properly... actually the layout shows only hearts and its doesnt matter which icon you put into it...

**Comment by wapchief** [comment]
Sorry ! I tested the available. Please refer to the sample.

Use mipmap resources problems may occur. Please replace mipmap>drawable

```
        mHeartLayout.setDrawableIds(new int[]{R.drawable.ic_launcher_round,R.drawable.ic_launcher_round,R.drawable.ic_launcher_round,R.drawable.ic_launcher_round});

        mImageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mHeartLayout.addFavor();
            }
        });
```

**Comment by wapchief** [comment]
I found the problem, he only on the simulator is available, I will be in the next version to modify this problem.

**Comment by Jenia3377543** [comment]
i have fixed the issue, so there are few things you can do. if you dont change the color of drawable its works fine
